version: "3.8"
services:
  frontend:
    build: ./frontend
    image: frontend
    restart: always
    networks:
      - sub-etha
  backend:
    build: ./api
    image: api
    restart: always
    networks:
      - sub-etha
  revproxy:
    build: ./reverseproxy
    image: reverseproxy
    restart: always
    networks:
      - sub-etha
    ports:
      - "80:80"
networks:
  sub-etha:
